const {chromium}=require('C:/Users/Sebas/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const path=require('node:path');
const fs=require('node:fs');
const {pathToFileURL}=require('node:url');
const assert=require('node:assert/strict');
const OUT=path.join(__dirname,'checks');fs.mkdirSync(OUT,{recursive:true});
(async()=>{
 const browser=await chromium.launch({channel:'msedge',headless:true});
 const page=await browser.newPage({viewport:{width:1024,height:900}});page.setDefaultTimeout(6000);
 const errors=[],requests=[],results=[];
 page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(/^https?:/.test(r.url()))requests.push(r.url());});
 const click=a=>page.locator('[data-a="'+a+'"]').filter({visible:true}).first().click();
 const save=type=>page.locator('[data-form="'+type+'"] button[type=submit]').click();
 const wine=id=>page.locator('[data-a=wine][data-id="'+id+'"]').first().click();
 const openDetails=()=>page.locator('details[data-optional=entry]>summary').click();
 const shot=name=>page.screenshot({path:path.join(OUT,name+'.png'),fullPage:true});
 const pass=name=>{results.push(name);console.log('PASS:',name);};
 try{
  await page.goto(pathToFileURL(path.join(__dirname,'walkthrough.html')).href);
  await page.getByRole('heading',{name:'My wines',exact:true}).waitFor();
  await shot('desktop-my-wines');await wine('cr23');await shot('desktop-wine-record');
  assert.equal(await page.locator('.wj-record-history .wj-entry').count(),2);
  await click('log');await shot('desktop-quick-entry');
  assert.equal(await page.locator('[data-optional=entry]').getAttribute('open'),null);
  await save('entry');assert.equal(await page.locator('.wj-record-history .wj-entry').count(),3);
  assert.match(await page.locator('.wj-entry').first().innerText(),/Everyday entry/);
  await page.locator('.wj-entry').first().locator('[data-a=edit-entry]').click();
  await page.locator('[data-draft=notes]').fill('Quick save, remembered later.');await save('entry');
  assert.equal(await page.locator('.wj-record-history .wj-entry').count(),3);
  assert.match(await page.locator('.wj-entry').first().innerText(),/Quick save, remembered later/);
  pass('Wine + date creates one standalone entry; later notes update that same entry.');
  await click('rating');await page.locator('[name=rating]').selectOption('4');await save('rating');
  assert.equal(await page.locator('.wj-record-history .wj-entry').count(),3);
  assert.equal(await page.locator('.wj-rating-value').innerText(),'4.0');
  await click('rating');assert.equal(await page.locator('.wj-rating-history li').count(),3);
  await shot('desktop-rating-history');await save('rating');await click('rating');
  assert.equal(await page.locator('.wj-rating-history li').count(),3);
  await click('rating-back');await click('return-wine');
  await page.locator('[data-live=sort]').selectOption('rating');
  assert.equal(await page.locator('.wj-wine-card').first().getAttribute('data-id'),'hm23');
  pass('Current release rating, retained revision history, no duplicate revisions or drinking entries, rating sort.');
  await page.reload();await wine('cr23');await click('log');
  await page.locator('[data-draft=notes]').fill('Keep my quick note');await openDetails();
  await page.locator('[data-location=entry]').fill('Sam’s house');await click('inline-new');
  await page.locator('[data-inline=title]').fill('A new dinner');await shot('desktop-inline-occasion');
  await click('inline-cancel');assert.equal(await page.locator('[data-draft=notes]').inputValue(),'Keep my quick note');
  await click('inline-new');await page.locator('[data-inline=title]').fill('A new dinner');
  await page.locator('[data-inline=date]').fill('2026-08-12');await page.locator('[data-location=inline]').fill('Bar Sol');
  await save('entry');await page.getByRole('heading',{name:'A new dinner',exact:true}).waitFor();
  await page.locator('.wj-occasion-wine [data-a=edit-entry]').click();
  assert.equal(await page.locator('[data-draft=date]').inputValue(),'2026-09-14');
  assert.equal(await page.locator('[data-location=entry]').inputValue(),'Sam’s house');
  assert.equal(await page.locator('[data-draft=notes]').inputValue(),'Keep my quick note');
  await click('cancel-capture');pass('Inline occasion cancel/save preserves quick notes and independent drinking date and place.');
  await click('occasion-add-wine');await page.locator('[data-a=method][data-id=photo]').click();await click('sample-photo');
  await wine('son23');await click('log');await save('entry');assert.equal(await page.locator('.wj-occasion-wine').count(),2);
  pass('Saved occasion -> identify a new wine -> log -> return to the same scrapbook.');
  await click('occasions');await click('new-occasion');
  await page.locator('[data-occasion=title]').fill('Test dinner');await page.locator('[data-occasion=date]').fill('2026-08-10');
  await page.locator('[data-location=occasion]').fill('Alex’s house');await page.locator('[data-occasion=notes]').fill('Preserve the parent draft');
  await click('draft-add-wine');await click('cancel-capture');assert.equal(await page.locator('[data-occasion=title]').inputValue(),'Test dinner');
  await click('draft-add-wine');await wine('cr23');await click('log');
  assert.equal(await page.locator('[data-draft=date]').inputValue(),'2026-08-10');
  await page.locator('[data-draft=notes]').fill('First staged wine');await save('entry');
  await click('draft-add-wine');await click('manual');await page.locator('[data-manual=name]').fill('My test bottle');
  await page.locator('[data-manual=producer]').fill('Test producer');await page.locator('[data-manual=vintage]').fill('2022');
  const photo={name:'cover.png',mimeType:'image/png',buffer:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jOioAAAAASUVORK5CYII=','base64')};
  await page.locator('[data-cover]').setInputFiles(photo);await page.locator('img.wj-cover-preview').waitFor();
  assert.equal(await page.locator('[data-manual=name]').inputValue(),'My test bottle');
  await save('manual');await save('entry');assert.equal(await page.locator('.wj-staged-entry').count(),2);
  await click('library');await click('keep-editing');assert.equal(await page.locator('.wj-staged-entry').count(),2);
  assert.equal(await page.locator('[data-occasion=notes]').inputValue(),'Preserve the parent draft');
  await save('occasion');assert.equal(await page.locator('.wj-occasion-wine').count(),2);
  await page.locator('.wj-occasion-wine').filter({hasText:'My test bottle'}).locator('[data-a=wine]').click();
  assert.equal(await page.locator('.wj-cover-art img').evaluate(e=>e.naturalWidth),1);
  pass('Occasion draft -> multiple wines including manual cover; parent retained, one final save.');
  await click('log');await openDetails();
  await page.locator('[data-files=entry]').setInputFiles({name:'bad.txt',mimeType:'text/plain',buffer:Buffer.from('test')});
  assert.match(await page.locator('[role=alert]').innerText(),/Choose JPEG/);
  await page.locator('[data-files=entry]').setInputFiles(photo);await page.locator('img.wj-media-preview').waitFor();
  await save('entry');await page.locator('.wj-entry').first().locator('[data-a=edit-entry]').click();
  assert.equal(await page.locator('img.wj-media-preview').evaluate(e=>e.naturalWidth),1);
  await click('remove-memory');assert.equal(await page.locator('img.wj-media-preview').count(),0);await save('entry');
  pass('Photo type errors, local preview, retained entry media, and remove memory.');
  await click('log');await openDetails();await page.locator('[data-a=place-open][data-ctx=entry]').click();
  await page.locator('[data-place-query]').fill('Bar Sol');assert.equal(await page.locator('.wj-place-result').count(),2);
  await page.locator('[data-a=place-select][data-id="sample:bar-sol-napa"]').click();
  await page.locator('[data-location=entry]').fill('My house');assert.match(await page.locator('.wj-location').first().innerText(),/Use any personal label/);
  await click('cancel-capture');pass('Place picker selection can be replaced by a private label.');
  await click('account');await click('signout');await click('find');await wine('cr23');
  assert.equal(await page.locator('.wj-entry').count(),0);assert.equal(await page.locator('.wj-rating-value').count(),0);
  await click('log');await page.locator('[data-draft=notes]').fill('Guest note');await save('entry');
  await click('auth-back');assert.equal(await page.locator('[data-draft=notes]').inputValue(),'Guest note');
  await save('entry');await page.locator('[data-form=auth] input').fill('test@example.com');await save('auth');
  assert.match(await page.locator('.wj-entry').first().innerText(),/Guest note/);
  pass('Guest lookup hides private history; sign-in back/resumption preserves the entry.');
  await click('browse');await page.locator('[data-a=browse-tab][data-id=you]').click();assert.match(await page.locator('main').innerText(),/Future discovery concept/i);
  await page.locator('[data-a=browse-tab][data-id=trending]').click();assert.match(await page.locator('main').innerText(),/Future community concept/i);
  await click('guides');await page.locator('[data-a=open-guide][data-id=regions]').click();await page.locator('[data-a=browse-related][data-query=Champagne]').click();
  assert.equal(await page.locator('.wj-wine-card').count(),1);
  pass('Browse, future discovery concepts, guides, and related catalog filters remain connected.');
  await page.reload();
  for(const width of [320,390,768,1024,1440]){
   await page.setViewportSize({width,height:900});
   for(const route of ['library','wine','entry','inline','occasions','scrapbook','rating','browse','guides']){
    if(route==='library')await click('library');
    if(route==='wine')await wine('cr23');
    if(route==='entry')await click('log');
    if(route==='inline'){await openDetails();await click('inline-new');}
    if(route==='occasions'){await click('cancel-capture');await click('occasions');}
    if(route==='scrapbook')await page.locator('[data-a=occasion][data-id=o1]').click();
    if(route==='rating'){await page.locator('.wj-occasion-wine [data-a=wine]').first().click();await click('rating');}
    if(route==='browse')await click('browse');
    if(route==='guides')await click('guides');
    const size=await page.locator('#wine-journal-v3').evaluate(e=>({width:e.clientWidth,scroll:e.scrollWidth,body:document.body.scrollWidth}));
    assert.ok(size.scroll<=size.width+1&&size.body<=width+1,route+' overflow at '+width+' '+JSON.stringify(size));
    const bad=await page.locator('main').evaluate(m=>Array.from(m.querySelectorAll('button,input,textarea,select')).filter(e=>e.getClientRects().length).filter(e=>{const r=e.getBoundingClientRect();return r.left< -1||r.right>window.innerWidth+1;}).map(e=>e.outerHTML.slice(0,180)));
    assert.deepEqual(bad,[],route+' controls outside viewport at '+width);
    if(width===390||width===1024)await shot(width+'-'+route);
   }
  }
  await page.reload();await page.setViewportSize({width:390,height:900});
  await page.keyboard.press('Tab');assert.equal(await page.locator(':focus').count(),1);
  await page.keyboard.press('Enter');await page.getByRole('heading',{name:'My wines',exact:true}).waitFor();
  assert.deepEqual(errors,[]);assert.deepEqual(requests,[]);
  pass('Nine screen states at 320/390/768/1024/1440, keyboard activation, no runtime errors or external requests.');
  fs.writeFileSync(path.join(OUT,'results.json'),JSON.stringify({passed:results,errors,externalRequests:requests},null,2));
 }catch(error){await shot('failure');console.error('SCREEN:',await page.locator('main').innerText());console.error('ERRORS:',errors);throw error;}
 finally{await browser.close();}
})().catch(e=>{console.error(e);process.exit(1)});
